set -g pane-active-border-style 'fg=#7aa2f7,bg=default'
set -g pane-border-style 'fg=#444b6a,bg=default'

set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g status-style 'bg=#1a1b26,fg=#c0caf5'
set -g status-left '#{?client_prefix,#[fg=#1a1b26]#[bg=#7aa2f7]#[bold],#[fg=#1a1b26]#[bg=#449dab]} #{session_name} #[fg=default]#[bg=default]   '
set -g status-right ''
set -g status-justify left
set -g status-left-length 40
set -g status-right-length 0

setw -g window-status-format ' #{window_index}:#{window_name} '
setw -g window-status-style 'fg=#787c99,bg=default'
setw -g window-status-current-format ' #{window_index}:#{window_name} '
setw -g window-status-current-style 'fg=#1a1b26,bg=#7aa2f7,bold'

bind-key & kill-window # skipp "kill-window" (y/n)" propt
bind-key u display-popup -h 30 -E # show popup

bind-key "E" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""
