[default_session]
startup_command = '''nvim --cmd 'autocmd VimEnter * lua require("snacks.picker").files()' '''
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "y"

[[session]]
name = "tmux config"
path = "~/"
startup_command = "nvim .tmux.conf"
preview_command = "bat --color=always ~/.tmux.conf"

[[session]]
name = "sesh config"
path = "~/.config/sesh/"
startup_command = "chezmoi edit sesh.toml"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "bash config"
path = "~/"
startup_command = "chezmoi edit .bashrc"
preview_command = "bat --color=always ~/.bashrc"
